### ISSUE TITLE
Support Psalm 5

### ISSUE THREAD

**Issue by jack-worman** [marartner/psalm-no-empty#2]
title

**Comment by flodnv** [comment]
Hi, could you please update this library to have support for Psalm 6? 🙏  cc @marartner

**Comment by marartner** [comment]
@flodnv I'm not actively using this myself anymore since we switched to PHPStan a while ago, but since other people still are, it seems worth maintaining. So: Thanks for bringing this to my attention. 

I just bumped the required Psalm version and it seems to still work as is. Thus, new version released, enjoy!

**Comment by flodnv** [comment]
Awesome, thanks a lot!
